kind: pipeline
type: docker
name: production
steps:
  - name: submodules
    image: alpine/git
    commands:
    - git submodule update --init --recursive


  - name: restore-cache
    image: meltwater/drone-cache
    settings:
      backend: filesystem
      cache_key: volume
      archive_format: zstd
      restore: true
      mount:
        - ./node_modules
        - ./_npxcache
        - ./.vercel
    volumes:
      - name: cache
        path: /tmp/cache
  - name: install-dependencies
    image: node:18
    commands:
      - npm config set registry https://repo.nju.edu.cn/repository/npm/
      - npm install
      - npx --cache _npxcache vercel --version
  - name: link-vercel
    image: node:18
    environment:
      VERCEL_TOKEN:
        from_secret: vercel_access_token
    commands:
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN link --yes --project=my-blog
  - name: rebuild-cache
    image: meltwater/drone-cache
    settings:
      backend: filesystem
      cache_key: volume
      archive_format: zstd
      rebuild: true
      mount:
        - ./node_modules
        - ./_npxcache
        - ./.vercel
    volumes:
      - name: cache
        path: /tmp/cache
  - name: build-production
    image: node:18
    environment:
      VERCEL_TOKEN:
        from_secret: vercel_access_token
    commands:
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN pull --yes --environment=production
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN build --prod --yes
  - name: deploy-production
    image: node:18
    environment:
      VERCEL_TOKEN:
        from_secret: vercel_access_token
    commands:
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN deploy --prebuilt --yes --prod
trigger:
  branch:
    - main
volumes:
  - name: cache
    host:
      path: /root/drone/cache
