---
kind: pipeline
type: docker
name: production

clone:
  depth: 0

steps:
  - name: submodules
    image: alpine/git
    commands:
    - git submodule update --init --recursive
    
  - name: fix-update-time
    image: alpine/git
    commands:
    - git ls-files -z | while read -d '' path; do touch -d "$(git log -1 --format="@%ct" "$path")" "$path"; done

  - name: restore-cache
    image: meltwater/drone-cache
    settings:
      backend: filesystem
      cache_key: volume
      archive_format: zstd
      restore: true
      mount:
        - ./node_modules
        - ./_npxcache
        - ./.vercel
        - ./pandoc
    volumes:
      - name: cache
        path: /tmp/cache
  - name: install-dependencies
    image: node:19
    commands:
      - npm config set registry https://repo.nju.edu.cn/repository/npm/
      - npm install
      - npx --cache _npxcache vercel --version
      - mkdir pandoc
      - touch pandoc/pandoc.deb
      - if [[ $(sha256sum pandoc/pandoc.deb) = "e5276b8ec6f2f25d85caa7f529a09117dcd346e04a8a5dcca755c58043b4a6f9  pandoc/pandoc.deb" ]]; then echo "Signature OK"; else rm pandoc/pandoc.deb; wget https://ghproxy.com/github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb -O pandoc/pandoc.deb; fi
  - name: link-vercel
    image: node:19
    environment:
      VERCEL_TOKEN:
        from_secret: vercel_access_token
    commands:
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN link --yes --project=my-blog
      - echo "🎉 Successful! (hopefully)"
  - name: rebuild-cache
    image: meltwater/drone-cache
    settings:
      backend: filesystem
      cache_key: volume
      archive_format: zstd
      rebuild: true
      mount:
        - ./node_modules
        - ./_npxcache
        - ./.vercel
        - ./pandoc
    volumes:
      - name: cache
        path: /tmp/cache
  - name: build-production
    image: node:19
    environment:
      VERCEL_TOKEN:
        from_secret: vercel_access_token
    commands:
      - dpkg -i pandoc/pandoc.deb
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN pull --yes --environment=production
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN build --prod --yes
  - name: deploy-production
    image: node:19
    environment:
      VERCEL_TOKEN:
        from_secret: vercel_access_token
    commands:
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN deploy --prebuilt --yes --prod
trigger:
  branch:
    include:
      - main
    exclude:
      - renovate/*
  event:
    include:
    - custom
    - push
    - pull_request
    exclude:
    - cron
  cron:
    exclude:
    - renovate
volumes:
  - name: cache
    host:
      path: /root/drone/cache
---
kind: pipeline
type: docker
name: renovate

steps:
  - name: renovate-bot
    image: renovate/renovate:latest
    environment:
      RENOVATE_TOKEN:
        from_secret: renovate_bot_pat
      RENOVATE_AUTODISCOVER: 'true'
      RENOVATE_ENDPOINT: 'https://git.6leo6.com'
      RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
      RENOVATE_PLATFORM: "gitea"
      GITHUB_COM_TOKEN:
        from_secret: github_user_token
    commands:
      - renovate

trigger:
  event:
    include:
      - cron
      - custom
      - push
      - pull_request