---
kind: pipeline
type: docker
name: production
steps:
  - name: submodules
    image: alpine/git
    commands:
    - git submodule update --init --recursive


  - name: restore-cache
    image: meltwater/drone-cache
    settings:
      backend: filesystem
      cache_key: volume
      archive_format: zstd
      restore: true
      mount:
        - ./node_modules
        - ./_npxcache
        - ./.vercel
    volumes:
      - name: cache
        path: /tmp/cache
  - name: install-dependencies
    image: node:19
    commands:
      - npm config set registry https://repo.nju.edu.cn/repository/npm/
      - npm install
      - npx --cache _npxcache vercel --version
  - name: link-vercel
    image: node:19
    environment:
      VERCEL_TOKEN:
        from_secret: vercel_access_token
    commands:
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN link --yes --project=my-blog
  - name: rebuild-cache
    image: meltwater/drone-cache
    settings:
      backend: filesystem
      cache_key: volume
      archive_format: zstd
      rebuild: true
      mount:
        - ./node_modules
        - ./_npxcache
        - ./.vercel
    volumes:
      - name: cache
        path: /tmp/cache
  - name: build-production
    image: node:19
    environment:
      VERCEL_TOKEN:
        from_secret: vercel_access_token
    commands:
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN pull --yes --environment=production
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN build --prod --yes
  - name: deploy-production
    image: node:19
    environment:
      VERCEL_TOKEN:
        from_secret: vercel_access_token
    commands:
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN deploy --prebuilt --yes --prod
trigger:
  branch:
    - main
  event:
    include:
    - push
    - pull_request
    exclude:
    - cron
  cron:
    exclude:
    - renovate
volumes:
  - name: cache
    host:
      path: /root/drone/cache
---
kind: pipeline
type: docker
name: renovate

steps:
  - name: renovate-bot
    image: renovate/renovate:latest
    environment:
      RENOVATE_TOKEN:
        from_secret: renovate_bot_pat
      RENOVATE_AUTODISCOVER: 'true'
      RENOVATE_ENDPOINT: 'https://git.6leo6.com'
      RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
      RENOVATE_PLATFORM: "gitea"
    commands:
      - renovate

trigger:
  event:
    include:
      - cron
      - custom
      - push
      - pull_request