# This file is used for woodpecker ci to build and deploy site.

pipeline:
  production-build:
    image: node:16
    commands:
      - npm install
      - npm install --location=global vercel
      - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
      - vercel --token=$VERCEL_TOKEN build --prod --yes
      
  production-deploy:
    image: node:16
    commands:
      - npm install --location=global vercel
      - vercel --token=$VERCEL_TOKEN deploy --prebuilt --yes --prod
    secrets: [ VERCEL_TOKEN ]