# This file is used for woodpecker ci to build and deploy site.

pipeline:
  build:
    image: node:16-slim
    commands:
      - npm install --location=global cnpm --registry=https://registry.npmmirror.com
      - cnpm install
      - cnpm install js-yaml --save
      - cnpm run build
      
  deploy:
    image: node:16-slim
    commands:
      - npm install --location=global cnpm --registry=https://registry.npmmirror.com
      - cnpm install --location=global vercel
      - vercel --token=$VERCEL_TOKEN
    secrets: [ VERCEL_TOKEN ]