# This file is used for woodpecker ci to build and deploy site.

pipeline:
  build:
    image: node:16
    commands:
      - npm install --registry=https://registry.npmmirror.com
      - npm install --registry=https://registry.npmmirror.com --location=global vercel
      - vercel --token=$VERCEL_TOKEN build --prod --yes
      
  deploy:
    image: node:16
    commands:
      - npm install --registry=https://registry.npmmirror.com --location=global vercel
      - vercel --token=$VERCEL_TOKEN deploy --prebuilt --yes
    secrets: [ VERCEL_TOKEN ]