# Configuration:
# https://volantis.js.org/v6/theme-settings/

cdn_system:
  # CDN 优先级 从高到低排序 写入 priority 列表即表示启用(enable)
  priority: [custom, local, cdnjs, npm, static]
  # ========================================================================
  # cdn数据配置文件见 "theme/_cdn.yml", 可以在 source/_data/cdn.yml 覆盖 theme/_cdn.yml
  # 变量说明：
  # 以下变量只能在 `prefix` 中使用。
  # ${site_root}                站点根目录 一般是 "/"
  # 以下变量只能在 `format` 中使用。
  # ${prefix}                   CDN 链接前缀
  # ${name}                     package 名称 见 "theme/_cdn.yml"
  # ${version}                  package 版本 见 "theme/_cdn.yml"
  # ${file}                     文件路径 见 "theme/_cdn.yml"
  # ${min_file}                 文件路径 ${file} 后添加 .min. (jsdelivr、cdnjs 官方自带压缩)
  # ${timestamp}                Hexo运行时的时间戳(eg：1661246702300), 可用于静态资源版本控制 format: ${prefix}${file}?v=${timestamp}
  system_config:
    # 自定义配置 使用 "theme/_cdn.yml" 中的名称作为配置项的键
    custom:
      #volantis_style: /css/style.css
      #volantis_app: /js/app.js

    # 主题 /js与/css目录 （一般放在本地，可以在此处配置站点CDN）,"theme/_cdn.yml" 中以 "volantis_" 开头的名称
    # Tip: 在本配置文件中 匹配以 "volantis-local" 开头的链接路径替换为该格式的前缀开头 prefix
    local:
      # CDN 链接前缀
      prefix: ${site_root}
      # local CDN 格式
      format: ${prefix}${file}
    # npm
    # https://www.npmjs.com/
    # Tip: 在本配置文件中 匹配以 "volantis-npm" 开头的链接路径替换为该格式的前缀开头 prefix
    npm:
      # CDN 链接前缀
      # prefix: https://unpkg.com
      prefix: https://jsd.cdn.zzko.cn/npm
      # npm CDN 格式
      format: ${prefix}/${name}@${version}/${file}
    # volantis static 静态资源文件 npm 包 CDN 地址
    # https://github.com/volantis-x/volantis-static
    # Tip: 在本配置文件中 匹配以 "volantis-static" 开头的链接路径替换为该格式的前缀开头 prefix
    static:
      # CDN 链接前缀
      # prefix: https://unpkg.com/volantis-static@0.0.1660614606622
      prefix: https://jsd.cdn.zzko.cn/npm/volantis-static@0.0.1660614606622
      # volantis-static CDN 格式
      format: ${prefix}/libs/${name}/${file}
    # cdnjs
    # https://cdnjs.com/
    # Tip: 在本配置文件中 匹配以 "volantis-cdnjs" 开头的链接路径替换为该格式的前缀开头 prefix
    cdnjs:
      # CDN 链接前缀
      prefix: https://cdnjs.cloudflare.com/ajax/libs
      # cdnjs CDN 格式
      format: ${prefix}/${name}/${version}/${min_file}
  # ========================================================================


plugins:
  # 代码高亮
  code_highlight: highlightjs # highlightjs or prismjs
  # highlight.js
  highlightjs:
    copy_code: true
    # 如果开启以下配置, hexo.config.highlight.enable 需要设置为 false ; hexo.config.highlight.enable 设置为 true, 则以下配置无效
    # # 不再支持 v11.1.0 以下版本
    js: https://jsd.cdn.zzko.cn/npm/@highlightjs/cdn-assets@11.7.0/highlight.min.js
    # Please set hexo.config.highlight.enable = false !!!
    css: https://jsd.cdn.zzko.cn/npm/@highlightjs/cdn-assets@11.7.0/styles/atom-one-dark-reasonable.min.css
    # # # more: https://www.jsdelivr.com/package/npm/@highlightjs/cdn-assets?path=styles
    
comments:
  service: waline
  waline:
    path: # 全局评论地址 目前设置全局评论地址后visitor失效,这是waline的问题
    serverURL: https://waline.6leo6.com
    placeholder: 发一条友善的评论~
    pageview: true # 浏览量统计
    comment: true  # 评论数统计
    imageUploader:
      api: https://www.imgtp.com/api/upload
      token: 
      resp: data.url
    avatar: robohash
    avatarCDN: https://sdn.geekzu.org/avatar/
    
search:
  enable: true
  service: hexo

custom_css:
  fontfamily:
    logofont:
      fontfamily: '"Varela Round", "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Varela Round'
      url: volantis-static/media/fonts/VarelaRound/VarelaRound-Regular.ttf # https://gcore.jsdelivr.net/gh/volantis-x/cdn-fonts/VarelaRound/VarelaRound-Regular.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: 'Noto Sans, "Varela Round", "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Noto Sans'
      url: https://mirrors.tuna.tsinghua.edu.cn/ctan/fonts/noto/truetype/NotoSans-Regular.ttf
      weight: normal
      style: normal
    codefont:
      fontfamily: '"JetBrains Mono", Menlo, UbuntuMono, Monaco'
      name: 'JetBrains Mono'
      url: https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono/web/woff2/JetBrainsMono-Regular.woff2
      weight: normal
      style: normal