# This file is used for woodpecker ci to build and deploy site.

pipeline:
  restore-cache:
    image: meltwater/drone-cache
    volumes:
      - /root/woodpecker/cache:/tmp/cache
    settings:
      backend: "filesystem"
      cache_key: "volume"
      archive_format: "gzip"
      restore: true
      mount:
        - ./node_modules
        - ./_npxcache
        - ./.vercel
  prepare:
    image: node:18
    commands:
      - npm config set registry https://repo.nju.edu.cn/repository/npm/ # 修改源
      - npm install
      - npx --cache _npxcache vercel --version
  vercel-link-project:
    image: node:18
    commands:
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN link --yes --project=my-blog
    secrets: [ VERCEL_TOKEN ]
  rebuild-cache:
    image: meltwater/drone-cache
    volumes:
      - /root/woodpecker/cache:/tmp/cache
    settings:
      backend: "filesystem"
      cache_key: "volume"
      archive_format: "gzip"
      rebuild: true
      mount:
        - ./node_modules
        - ./_npxcache
        - ./.vercel
  production-build:
    image: node:18
    commands:
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN pull --yes --environment=production
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN build --prod --yes
    secrets: [ VERCEL_TOKEN ]
  production-deploy:
    image: node:18
    commands:
      - npx --cache _npxcache vercel --token=$VERCEL_TOKEN deploy --prebuilt --yes --prod
    secrets: [ VERCEL_TOKEN ]