name: Deploy Blog

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
  
jobs:
  hexo-build-deploy:
    if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    environment:
      name: production
      url: ${{ steps.deploy-vercel.outputs.preview-url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
            
      - name: Fix File Modify Time
        run: git ls-files -z | while read -d '' path; do touch -d "$(git log -1 --format="@%ct" "$path")" "$path"; done
        
      - name: Install Node Dependencies
        run: npm install
        
      - name: Install Pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb -O pandoc.deb
          sudo dpkg -i pandoc.deb
          
      - name: Build
        run: npm run build
        
      - name: Deploy to Vercel
        id: deploy-vercel
        uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 

      
  hexo-build-preview:
    if: github.event_name == 'push' && github.ref_name != 'main'
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    environment:
      name: preview
      url: ${{ steps.deploy-vercel.outputs.preview-url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
            
      - name: Fix File Modify Time
        run: git ls-files -z | while read -d '' path; do touch -d "$(git log -1 --format="@%ct" "$path")" "$path"; done
        
      - name: Install Node Dependencies
        run: npm install
        
      - name: Install Pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb -O pandoc.deb
          sudo dpkg -i pandoc.deb

      - name: Build
        run: npm run build
        
      - name: Deploy to Vercel
        id: deploy-vercel
        uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args:  #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 
