name: Preview Deploy

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]
  
jobs:
  hexo-build-preview:
    if: github.ref_name != 'main'
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: '0'
          submodules: 'true'
      
      - name: Correct Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Asia/Shanghai"
      
      - name: Generate
        uses: 66Leo66/build-my-blog@v3

      - name: Deploy
        id: deploy
        uses: 66Leo66/push-to-vercel@v5
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-projectId: ${{ secrets.VERCEL_PROJECTID }}
          vercel-orgId: ${{ secrets.VERCEL_ORGID }}
          production: 'false'
          vercel-region: 'hkg1'
