name: Production Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
  
jobs:
  hexo-build-deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    environment:
      name: production
      url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: '0'
          submodules: 'true'
        
      - name: Generate
        uses: 66Leo66/build-my-blog@v2

      - name: Deploy
        id: deploy
        uses: 66Leo66/push-to-vercel@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-projectId: ${{ secrets.VERCEL_PROJECTID }}
          vercel-orgId: ${{ secrets.VERCEL_ORGID }}
          production: true
          vercel-region: 'hkg1'