name: Production Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
  
jobs:
  hexo-build-deploy:
    if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    environment:
      name: production
      url: ${{ steps.deploy-vercel.outputs.preview-url }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: '0'
          submodules: 'true'
        
      - name: Generate
        uses: 66Leo66/build-my-blog

      - name: test
        run: ls
      # - name: Deploy to Vercel
      #   env:
      #     VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      #   run: |
      #     echo "{\"version\": 3}" > .vercel/output/config.json
      #     npx vercel deploy --prebuilt --prod > url.txt